#!/usr/bin/env python

import sys
import os
import os.path
import shutil

if len(sys.argv) != 3:
    print 'Usage: [#] [filename]'
    print '\t#: assignment number'
    print '\tfilename: the correct file name'
    sys.exit(1)

fname = sys.argv[2]
assi  = 'A' + sys.argv[1]
print 'File name: ' + fname
print 'Assignment: ' + assi

rdir = '/v/filer4b/v38q001/sah2659/Dropbox/cs303e_p/'
dump = rdir + 'moss/mdump/'

c = 0
t = 0
for num in ('52218', '52226', '52227', '52228', '52229'):
    cdir = rdir + num + '/' + assi 
    for _, dirs, _ in os.walk(cdir):
        for dname in dirs:
            d5dir = cdir + '/' + dname
            epath = d5dir + '/' + fname
            t += 1
            print '%s\t%r' % (epath, os.path.exists(epath))
            if os.path.exists(epath):
                nname = dname + '.' + fname
                dest = dump + nname
                print '\t' + nname
                shutil.copy2(epath, dest)
                c += 1

print ''
print '%d Students' % t
print '%d Files Found and moved into dump' % c
