#!/usr/bin/env python
# upload grades.txt to UTCS Webturnin
# Seth Hoenig 2012 (seth.a.hoenig@gmail.com)

import os
import random
from gutilz import join_comment

url = 'https://turnin.microlab.cs.utexas.edu/turnin/webturnin.dll/upload'

def get_login_info():
    usrnm = raw_input('UTCS Username: ')
    passwd = raw_input('UTCS Password: ')
    course = raw_input('Course: ')
    assin = raw_input('Assignment #: ')
    return (usrnm, passwd, course, assin)

def login(usrnm, passwd):
    cmd = 'curl -c cookies.txt ' + \
        '-d \"username=' + usrnm + '\" ' + \
        '-d \"password=' + passwd + '\" ' + \
        '--insecure ' + \
        '-H "Expect:" ' + \
        '''"https://turnin.microlab.cs.utexas.edu/turnin/webturnin.dll/do_login"'''

    print 'cmd: %s' % cmd
    os.system(cmd)

# return a random happy comment
# def happy_comment():
#     phrases = ['Good Job!', 'Excellent Work!', 'Neato!']
#     return phrases[random.randint(0, len(phrases)-1)]

# read grades.txt and return a list of records
# a record is a tuple in the form: (utcsname, comment)
def slurp_grades():
    with open('./grades.txt') as gradesf:
        records = []
        for line in gradesf.readlines():
            sp = line.split()
            account = sp[1]
            comment = join_comment(sp)
            records.append( (account, comment) )
        return records



# THIS IS BROKEN :'(
# Webturnin does not provide any error messages at this point, so I think
# the files are technically getting uploaded, but not into the actual
# user directories
def upload_comments(u, p, c, a):
    for record in slurp_grades():
        if record[1] in ('',): # skip people with no comments
            continue
        # make an A#.txt file in /tmp for every comment file
        with open('/tmp/A' + a + '.txt', 'w') as tempf:
            # print record
            print >>tempf, record[1]
            # magical upload part
            cmd = 'curl -F "class=' + c  + '.GRADER' + '" ' + \
                '-F \"user=' + record[0] + '\" ' + \
                '-F \"file=@/tmp/A' + a + '.txt;filename=A'+ a + '.txt\" ' \
                '--insecure ' + \
                '-H "Expect:" ' + \
                '-b cookies.txt -c cookies.txt ' + \
                '--url \"' + url + '\" '
            print ''
            print ''
            print cmd + '\n'
            os.system(cmd)

# instead of uploading to Webturnin, just create the comment files
# with utcs-usernames appended to them
def create_comment_files(assignment):
    for record in slurp_grades():
        if record[1] in ('',): # skip people with no comments
            continue
        # make utcs-A#.txt file
        fname = record[0] + '-A' + assignment + '.txt'
        with open('/tmp/'+fname, 'w') as tempf:
            print >>tempf, record[1]

if __name__ == '__main__':
    #u, p, c, a = get_login_info()
    #login(u, p)
    #upload_comments(u, p, c, a)
    assi = raw_input('Assignemnt #: ')
    create_comment_files(assi)
